# Generated by Django 2.1.3 on 2019-01-03 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0004_accountmigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_db',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 5, 58, 15, 599347, tzinfo=utc), verbose_name='信息创建时间'),
        ),
    ]
