# Generated by Django 2.1.3 on 2019-02-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0009_discountmerchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmerchant',
            name='merchant_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='商家网站'),
        ),
        migrations.AlterField(
            model_name='discountmerchant',
            name='merchant_phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='联系电话'),
        ),
    ]
