# Generated by Django 2.1.7 on 2019-03-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0010_auto_20190218_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfiguration',
        ),
        migrations.RemoveField(
            model_name='emaildb',
            name='recID',
        ),
        migrations.RemoveField(
            model_name='emaildb',
            name='sendID',
        ),
        migrations.RemoveField(
            model_name='notification_db',
            name='recID',
        ),
        migrations.RemoveField(
            model_name='notification_db',
            name='sendID',
        ),
        migrations.DeleteModel(
            name='EmailDB',
        ),
        migrations.DeleteModel(
            name='Notification_DB',
        ),
    ]
