# Generated by Django 2.1.7 on 2019-03-06 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0012_auto_20190306_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmerchant',
            name='merchant_add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='商户加入时间'),
        ),
    ]
