# Generated by Django 2.1.7 on 2019-03-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0015_auto_20190306_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmerchant',
            name='merchant_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='商家介绍'),
        ),
    ]
