# Generated by Django 3.1.12 on 2021-08-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0019_discountmerchant_merchant_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountmerchant',
            name='operation_hours',
            field=models.CharField(max_length=50, null=True, verbose_name='商家开放时间'),
        ),
        migrations.AddField(
            model_name='discountmerchant',
            name='priority',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discountmerchant',
            name='sale',
            field=models.CharField(max_length=100, null=True, verbose_name='促销'),
        ),
    ]
