# Generated by Django 3.1.12 on 2021-08-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0020_auto_20210809_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountmerchant',
            name='promotion_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/usrImage/promotionImage', verbose_name='宣传图片'),
        ),
        migrations.AlterField(
            model_name='discountmerchant',
            name='operation_hours',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='商家开放时间'),
        ),
        migrations.AlterField(
            model_name='discountmerchant',
            name='priority',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountmerchant',
            name='sale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='促销'),
        ),
    ]
