# Generated by Django 3.1.12 on 2024-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0022_auto_20230824_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmerchant',
            name='merchant_image',
            field=models.ImageField(default=None, upload_to='img/merchants/'),
        ),
    ]
