# Generated by Django 3.1.12 on 2025-04-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0023_auto_20240903_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountmerchant',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='地址纬度'),
        ),
        migrations.AddField(
            model_name='discountmerchant',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='地址经度'),
        ),
    ]
