# Generated by Django 2.1.3 on 2018-12-02 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLFields',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fieldType', models.CharField(choices=[('text', 'text'), ('html', 'html'), ('img', 'img'), ('video', 'video'), ('iFrame', 'iFrame')], max_length=10, null=True)),
                ('fieldName', models.CharField(max_length=256)),
                ('fieldClass', models.CharField(max_length=256)),
                ('fieldInnerText', models.TextField(blank=True, null=True)),
                ('fieldContentSrc', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImgAttributes',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('filePath', models.FileField(upload_to='uploads/usrImage/')),
                ('RelatedField', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PublicSite.HTMLFields')),
            ],
        ),
        migrations.CreateModel(
            name='PageRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=100)),
                ('templates', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='htmlfields',
            name='PageId',
            field=models.ManyToManyField(to='PublicSite.PageRegister'),
        ),
    ]
