# Generated by Django 2.1.7 on 2019-02-23 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlexForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexform',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='表单标题'),
        ),
        migrations.AlterField(
            model_name='flexformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('digit', 'digit')], max_length=10, verbose_name='字段类型'),
        ),
        migrations.AlterField(
            model_name='flexformfield',
            name='max_len',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2000)], verbose_name='字数上限'),
        ),
        migrations.AlterField(
            model_name='flexformfield',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='字段名称'),
        ),
    ]
