# Generated by Django 2.1.7 on 2019-02-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlexForm', '0002_auto_20190223_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexformfield',
            name='name',
            field=models.CharField(max_length=100, verbose_name='字段名称'),
        ),
    ]
