# Generated by Django 2.2.1 on 2019-05-09 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlexForm', '0006_flexformfield_is_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexformdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuthAPI.UserProfile'),
        ),
    ]
