# Generated by Django 2.2.4 on 2019-08-23 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlexForm', '0008_auto_20190822_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexformdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuthAPI.UserProfile'),
        ),
    ]
