# Generated by Django 2.1.3 on 2019-02-14 11:09

import RecruitAPI.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAuthAPI', '0008_auto_20190106_0350'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('jobId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timeOfCreate', models.DateTimeField(auto_now_add=True)),
                ('jobName', models.CharField(default=None, max_length=50, verbose_name='职位名称')),
                ('description', models.CharField(default=None, max_length=400, verbose_name='职位介绍')),
                ('dueDate', models.DateTimeField(default=None, null=True, verbose_name='截止日期')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuthAPI.CSSADept', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('CVId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timeOfCreate', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default=None, max_length=400, verbose_name='申请原因')),
                ('hobby', models.CharField(default=None, max_length=400, verbose_name='兴趣爱好')),
                ('eduBackground', models.CharField(blank=True, default=None, max_length=400, null=True, verbose_name='教育背景')),
                ('inSchoolExp', models.CharField(default=None, max_length=400, verbose_name='校内经历')),
                ('outSchoolExp', models.CharField(blank=True, default=None, max_length=400, null=True, verbose_name='校外经历')),
                ('additionMsg', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('attachment', models.FileField(blank=True, default=None, null=True, upload_to=RecruitAPI.models._GetUserDir)),
                ('isOpened', models.BooleanField(blank=True, default=False, null=True)),
                ('isEnrolled', models.BooleanField(blank=True, default=False, null=True)),
                ('isOfferd', models.BooleanField(blank=True, default=False, null=True)),
                ('isReject', models.BooleanField(blank=True, default=None, null=True)),
                ('jobRelated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitAPI.JobList', verbose_name='相应职位')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
