# Generated by Django 2.1.3 on 2019-02-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitAPI', '0003_auto_20190218_0548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'permissions': (('view_all_resumes', 'Can view all resumes'),)},
        ),
    ]
