# Generated by Django 2.2.1 on 2019-05-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard_angel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpaccesslogmodel',
            name='status_code',
            field=models.CharField(default='200', max_length=3),
        ),
    ]
