# Generated by Django 2.1.3 on 2019-01-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='imageFileB64',
            field=models.ImageField(blank=True, null=True, upload_to='blog/blogpics'),
        ),
    ]
