# Generated by Django 2.1.3 on 2019-01-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='openToPublic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogdescription',
            name='blogOpenToPublic',
            field=models.BooleanField(default=True),
        ),
    ]
