# Generated by Django 2.2.1 on 2019-05-09 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogreviewed',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserAuthAPI.UserProfile'),
        ),
        migrations.AlterField(
            model_name='blogwrittenby',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserAuthAPI.UserProfile'),
        ),
    ]
