# Generated by Django 2.1.5 on 2019-01-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogTopPic',
            field=models.CharField(max_length=95),
        ),
    ]
