# Generated by Django 2.1.3 on 2019-01-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPI', '0002_auto_20190123_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogTopPic',
            field=models.CharField(max_length=95),
        ),
    ]
