# Generated by Django 2.1.3 on 2019-01-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPI', '0002_auto_20190110_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='createDate',
            field=models.DateTimeField(),
        ),
    ]
