# Generated by Django 2.1.3 on 2019-01-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPI', '0003_auto_20190110_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogOpen',
            field=models.BooleanField(default=True),
        ),
    ]
