# Generated by Django 2.1.3 on 2019-01-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPI', '0004_blog_blogopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogoldcontent',
            name='writtenDate',
            field=models.DateTimeField(default=None),
        ),
    ]
