# Generated by Django 3.1.12 on 2021-07-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0019_auto_20210709_1833'),
        ('CommunityAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=1000, verbose_name='举报原因')),
                ('resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('type', models.CharField(choices=[], max_length=100, verbose_name='举报类型')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_created_by', to='UserAuthAPI.userprofile')),
                ('resolvedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_resolved_by', to='UserAuthAPI.userprofile')),
                ('targetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommunityAPI.post')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='使用JSON表示额外的数据， 其格式根据type来变化')),
                ('read', models.BooleanField(default=False, verbose_name='用户是否已读该通知')),
                ('type', models.CharField(choices=[], max_length=100, verbose_name='通知类型')),
                ('targetId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CommunityAPI.post')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuthAPI.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FavouritePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommunityAPI.post')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuthAPI.userprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='favouritepost',
            constraint=models.UniqueConstraint(fields=('userId', 'postId'), name='userId_postId'),
        ),
    ]
