# Generated by Django 3.1.12 on 2021-07-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityAPI', '0002_auto_20210709_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(default='', max_length=20000, verbose_name='帖子正文'),
        ),
    ]
