# Generated by Django 3.1.12 on 2021-07-13 08:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0019_auto_20210709_1833'),
        ('CommunityAPI', '0003_auto_20210713_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contentId',
        ),
        migrations.AddField(
            model_name='content',
            name='editedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_edited_by', to='UserAuthAPI.userprofile'),
        ),
        migrations.AddField(
            model_name='content',
            name='editedTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='当前Content的创建时间（Post的修改时间）'),
        ),
    ]
