# Generated by Django 3.1.12 on 2021-07-13 18:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityAPI', '0004_auto_20210713_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='imageUrls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, size=None, verbose_name='帖子中出现的url'),
        ),
    ]
