# Generated by Django 3.1.12 on 2021-07-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityAPI', '0005_auto_20210714_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='postId',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='favouritepost',
            old_name='postId',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='favouritepost',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='targetId',
            new_name='targetPost',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tagId',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='targetId',
            new_name='targetPost',
        ),
    ]
