# Generated by Django 3.1.12 on 2021-07-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityAPI', '0006_auto_20210714_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CommunityAPI.tag'),
        ),
    ]
