# Generated by Django 3.1.12 on 2021-07-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityAPI', '0008_auto_20210717_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_censor_post', 'Can censor posts'),)},
        ),
    ]
