# Generated by Django 3.1.12 on 2021-07-21 07:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0019_auto_20210709_1833'),
        ('CommunityAPI', '0008_auto_20210717_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='imageUrls',
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/community/post_image', verbose_name='用户上传的图片')),
                ('uploadTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='本图片的上传时间')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='postimage_uploader', to='UserAuthAPI.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='images',
            field=models.ManyToManyField(to='CommunityAPI.PostImage', verbose_name='帖子关联的图片'),
        ),
    ]
