# Generated by Django 3.1.12 on 2021-07-21 13:14

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityAPI', '0009_auto_20210721_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='uploads/community/post_image', verbose_name='用户上传的图片'),
        ),
    ]
