# Generated by Django 3.1.12 on 2021-07-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityAPI', '0010_auto_20210721_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('censor_post', 'Can censor post'),)},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('REPLY', '回复'), ('CENSOR', '屏蔽')], max_length=100, verbose_name='通知类型'),
        ),
    ]
