# Generated by Django 3.1.12 on 2021-08-02 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityAPI', '0016_auto_20210802_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知的创建时间'),
        ),
    ]
