# Generated by Django 3.1.12 on 2021-08-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityAPI', '0017_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('SPAM', '垃圾/恶意营销'), ('FALSE_INFORMATION', '不实/有害消息'), ('PERSONAL_ATTACK', '人身攻击'), ('PLAGIARISM', '内容抄袭'), ('HATRED', '宣扬仇恨'), ('ILLEGAL', '违法内容')], max_length=100, verbose_name='举报类型'),
        ),
    ]
