# Generated by Django 3.1.12 on 2021-10-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityAPI', '0018_auto_20210813_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxMiniProgramData',
            fields=[
                ('type', models.IntegerField(choices=[(1, 'Access Token')], primary_key=True, serialize=False, verbose_name='数据类型')),
                ('data', models.JSONField(verbose_name='数据')),
            ],
        ),
    ]
