# Generated by Django 3.1.12 on 2026-08-25 09:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAuthAPI', '0020_delete_useracademic'),
        ('CommunityAPI', '0019_wxminiprogramdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('normalized_name', models.CharField(editable=False, max_length=150)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('teacher', models.CharField(max_length=100)),
                ('normalized_teacher', models.CharField(editable=False, max_length=100)),
                ('college', models.CharField(max_length=150)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('dedupe_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('rating_sum', models.PositiveIntegerField(default=0)),
                ('rating_average', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.CharField(max_length=500)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('audit_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16)),
                ('audit_message', models.CharField(blank=True, default='', max_length=500)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseReviewLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('response_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InteractionMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIKE_POST', 'Liked your post'), ('LIKE_COMMENT', 'Liked your comment'), ('LIKE_REVIEW', 'Liked your review'), ('COMMENT_POST', 'Commented on your post'), ('REPLY_COMMENT', 'Replied to your comment'), ('AUDIT_REJECTED', 'Content audit rejected')], max_length=32)),
                ('snippet', models.CharField(blank=True, default='', max_length=120)),
                ('cover', models.URLField(blank=True, default='')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiniProgramProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mini_program_profile', serialize=False, to='UserAuthAPI.userprofile')),
                ('nickname', models.CharField(blank=True, default='', max_length=30)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('college', models.CharField(blank=True, default='', max_length=150)),
                ('wechat_openid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostExtension',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mini_program_extension', serialize=False, to='CommunityAPI.post')),
                ('section', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('audit_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16)),
                ('audit_message', models.CharField(blank=True, default='', max_length=500)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadAsset',
            fields=[
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mini_program_upload', serialize=False, to='CommunityAPI.postimage')),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('audit_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('bound_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_program_uploads', to='UserAuthAPI.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_program_likes', to='CommunityAPI.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_program_post_likes', to='UserAuthAPI.userprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='postextension',
            index=models.Index(fields=['section', 'audit_status', 'deleted_at'], name='mini_post_public_idx'),
        ),
        migrations.AddField(
            model_name='interactionmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_program_messages', to='UserAuthAPI.userprofile'),
        ),
        migrations.AddField(
            model_name='interactionmessage',
            name='root_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_program_root_messages', to='CommunityAPI.post'),
        ),
        migrations.AddField(
            model_name='interactionmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_program_sent_messages', to='UserAuthAPI.userprofile'),
        ),
        migrations.AddField(
            model_name='interactionmessage',
            name='target_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_program_messages', to='CommunityAPI.post'),
        ),
        migrations.AddField(
            model_name='interactionmessage',
            name='target_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='MiniProgramAPI.coursereview'),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuthAPI.userprofile'),
        ),
        migrations.AddField(
            model_name='coursereviewlike',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='MiniProgramAPI.coursereview'),
        ),
        migrations.AddField(
            model_name='coursereviewlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_program_review_likes', to='UserAuthAPI.userprofile'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='MiniProgramAPI.course'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_program_course_reviews', to='UserAuthAPI.userprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_program_created_courses', to='UserAuthAPI.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='mini_unique_user_post_like'),
        ),
        migrations.AddIndex(
            model_name='interactionmessage',
            index=models.Index(fields=['recipient', 'is_read', '-id'], name='mini_message_unread_idx'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('user', 'key', 'method', 'path'), name='mini_unique_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='coursereviewlike',
            constraint=models.UniqueConstraint(fields=('user', 'review'), name='mini_unique_user_review_like'),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='mini_unique_user_course_review'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['normalized_name'], name='mini_course_name_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['normalized_teacher'], name='mini_course_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-review_count', '-rating_average'], name='mini_course_hot_idx'),
        ),
    ]
