# Generated by Django 2.2 on 2019-04-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageCarousels',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(verbose_name='页面链接')),
                ('filePath', models.FileField(upload_to='site/homepage/carousel/', verbose_name='图片')),
                ('header', models.CharField(max_length=35, verbose_name='大标题')),
                ('description', models.CharField(max_length=100, verbose_name='大标题')),
            ],
        ),
    ]
