# Generated by Django 2.1.3 on 2018-12-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlfields',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='htmlfields',
            name='timestamp_create',
            field=models.DateTimeField(auto_now_add=True, default='2018-12-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imgattributes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imgattributes',
            name='styleAttr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imgattributes',
            name='timestamp_create',
            field=models.DateTimeField(auto_now_add=True, default='2018-12-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageregister',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pageregister',
            name='timestamp_create',
            field=models.DateTimeField(auto_now_add=True, default='2018-12-01'),
            preserve_default=False,
        ),
    ]
