# Generated by Django 2.1.3 on 2019-01-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0004_auto_20190103_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracademic',
            name='uniMajor',
            field=models.CharField(max_length=100, verbose_name='专业'),
        ),
    ]
