# Generated by Django 2.1.3 on 2019-01-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0005_auto_20190103_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='cssadept',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cssadept',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='public/department/', verbose_name='头像'),
        ),
    ]
