# Generated by Django 2.1.7 on 2019-03-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0013_auto_20190227_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cssarole',
            name='roleFlag',
            field=models.CharField(max_length=15),
        ),
    ]
