# Generated by Django 2.2 on 2019-04-30 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0016_auto_20190430_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cssacommitteprofile',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
