# Generated by Django 3.1.12 on 2023-08-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0019_auto_20210709_1833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAcademic',
        ),
    ]
