# Generated by Django 2.1.3 on 2018-12-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegacyDataAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacyusers',
            name='email',
            field=models.CharField(max_length=60, null=True, verbose_name='电子邮箱'),
        ),
    ]
