# Generated by Django 2.1.3 on 2018-12-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegacyDataAPI', '0003_auto_20181228_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legacyusers',
            name='identiyConfirmed',
        ),
        migrations.AddField(
            model_name='legacyusers',
            name='identityConfirmed',
            field=models.BooleanField(default=False, verbose_name='会员身份状态'),
        ),
    ]
