# Generated by Django 2.2.3 on 2019-07-31 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventAPI', '0019_auto_20190509_0759'),
        ('UserAuthAPI', '0018_auto_20190509_0506'),
        ('PrizeAPI', '0004_auto_20190724_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizePool',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('group_tag', models.CharField(max_length=250)),
                ('event_related', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventAPI.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuthAPI.UserProfile')),
            ],
        ),
    ]
