# Generated by Django 2.2 on 2019-04-16 07:40

import PhotoCompetition.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submissionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submissionTime', models.DateTimeField(auto_now_add=True)),
                ('deviceType', models.CharField(choices=[('MobilePhone', '手机'), ('Camera', '相机')], default='手机', max_length=30, null=True, verbose_name='设备')),
                ('categoryType', models.CharField(choices=[('Nature', '风景'), ('Culture', '人文')], default='风景', max_length=30, null=True, verbose_name='类别')),
                ('upload_photo', models.FileField(blank=True, default=None, null=True, upload_to=PhotoCompetition.models._GetUserDir, verbose_name='上传作品')),
                ('description', models.CharField(max_length=250, verbose_name='简单描述')),
                ('submissionUserId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
