# Generated by Django 2.2 on 2019-04-19 07:10

import PhotoCompetition.models
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoCompetition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.CharField(max_length=250, verbose_name='作品简述'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='upload_photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, default=None, null=True, upload_to=PhotoCompetition.models._GetUserDir, verbose_name='上传作品'),
        ),
    ]
