# Generated by Django 2.2.4 on 2019-08-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoCompetition', '0008_submissionvoting'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='themeType',
            field=models.CharField(choices=[('Beauty', '美的定义'), ('Water', '水的模样')], default='Beauty', max_length=30, null=True, verbose_name='主题类型'),
        ),
    ]
