# Generated by Django 2.2 on 2019-04-26 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disabled', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上次更新')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('html_body', models.TextField(default=None, null=True, verbose_name='正文')),
                ('is_pure_text', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailQuene',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('date_scheduled', models.DateTimeField(default=django.utils.timezone.now, verbose_name='设定发送时间')),
                ('receiver', models.EmailField(max_length=254, verbose_name='收件人')),
                ('priorty', models.IntegerField(choices=[('0', 'LOW'), ('1', 'NORMAL'), ('2', 'HIGH')], default=1, verbose_name='优先级')),
                ('state', models.IntegerField(choices=[(-1, 'Failed'), (0, 'On Quene'), (1, 'Sending'), (2, 'Success')], default=0, verbose_name='发送状态')),
                ('disabled', models.BooleanField(default=False)),
                ('mail_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostmanAPI.MailDraft', verbose_name='邮件名')),
            ],
        ),
        migrations.CreateModel(
            name='MailAttachments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('file_name', models.CharField(max_length=256, verbose_name='文件名')),
                ('file_type', models.CharField(choices=[('CSS', 'CSS'), ('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('DOCUMENT', 'DOCUMENT')], max_length=10, verbose_name='文件类型')),
                ('file', models.FileField(upload_to='public/email/attachments/%Y/%m/%d/', verbose_name='文件')),
                ('related_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostmanAPI.MailDraft', verbose_name='关联邮件')),
            ],
        ),
    ]
