# Generated by Django 2.2 on 2019-04-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostmanAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildraft',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='上次更新'),
        ),
    ]
