# Generated by Django 2.2 on 2019-04-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostmanAPI', '0002_auto_20190429_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailquene',
            name='priorty',
            field=models.IntegerField(choices=[(0, 'LOW'), (1, 'NORMAL'), (2, 'HIGH')], default=1, verbose_name='优先级'),
        ),
    ]
