AUDIT_PENDING = 'PENDING'
AUDIT_APPROVED = 'APPROVED'
AUDIT_REJECTED = 'REJECTED'

AUDIT_STATUS_CHOICES = (
    (AUDIT_PENDING, 'Pending'),
    (AUDIT_APPROVED, 'Approved'),
    (AUDIT_REJECTED, 'Rejected'),
)

SECTION_CONFESSION_WALL = 1

LIKE_POST = 1
LIKE_COMMENT = 2
LIKE_REVIEW = 3

MESSAGE_LIKE_POST = 'LIKE_POST'
MESSAGE_LIKE_COMMENT = 'LIKE_COMMENT'
MESSAGE_LIKE_REVIEW = 'LIKE_REVIEW'
MESSAGE_COMMENT_POST = 'COMMENT_POST'
MESSAGE_REPLY_COMMENT = 'REPLY_COMMENT'
MESSAGE_AUDIT_REJECTED = 'AUDIT_REJECTED'

MESSAGE_TYPE_CHOICES = (
    (MESSAGE_LIKE_POST, 'Liked your post'),
    (MESSAGE_LIKE_COMMENT, 'Liked your comment'),
    (MESSAGE_LIKE_REVIEW, 'Liked your review'),
    (MESSAGE_COMMENT_POST, 'Commented on your post'),
    (MESSAGE_REPLY_COMMENT, 'Replied to your comment'),
    (MESSAGE_AUDIT_REJECTED, 'Content audit rejected'),
)
