# Generated by Django 2.2.1 on 2019-05-08 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoCompetition', '0004_auto_20190430_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedSubmission',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('disabled', models.BooleanField(default=False)),
                ('aggregate_votes', models.IntegerField(default=0, verbose_name='获得票数')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotoCompetition.Submission', verbose_name='作品')),
            ],
        ),
    ]
