# Generated by Django 2.2.1 on 2019-05-09 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoCompetition', '0005_approvedsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submissionUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserAuthAPI.UserProfile'),
        ),
    ]
