# Generated by Django 2.2.1 on 2019-05-14 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0018_auto_20190509_0506'),
        ('PhotoCompetition', '0007_auto_20190509_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionVoting',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('user_IPv4', models.GenericIPAddressField()),
                ('votable_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotoCompetition.ApprovedSubmission')),
                ('voter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserAuthAPI.UserProfile')),
            ],
        ),
    ]
