# Generated by Django 2.1.3 on 2018-12-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0003_auto_20181202_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
