# Generated by Django 2.2.1 on 2019-05-14 05:08

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpAccessLogModel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('visitor_ipv4', models.GenericIPAddressField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('request_path', models.TextField()),
                ('request_query_string', models.TextField(default=None, null=True)),
                ('request_method', models.CharField(max_length=10)),
                ('request_META', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
