# Generated by Django 2.1.7 on 2019-03-02 11:10

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('host_password', models.CharField(max_length=200, null=True, verbose_name='发送方密码')),
                ('host_user', models.CharField(max_length=200, null=True, verbose_name='发送方用户')),
                ('port', models.IntegerField(verbose_name='端口')),
            ],
        ),
        migrations.CreateModel(
            name='EmailDB',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200, null=True, verbose_name='email内容')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='email标题')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='信息加入时间')),
                ('recID', models.ForeignKey(on_delete=models.DO_NOTHING, related_name='接信者id', to=settings.AUTH_USER_MODEL)),
                ('sendID', models.ForeignKey(on_delete=models.DO_NOTHING, related_name='发信者id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification_DB',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('content', models.CharField(max_length=200, null=True, verbose_name='站内信内容')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='站内信标题')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='信息加入时间')),
                ('recID', models.ForeignKey(on_delete=models.DO_NOTHING, related_name='接受者id', to=settings.AUTH_USER_MODEL)),
                ('sendID', models.ForeignKey(on_delete=models.DO_NOTHING, related_name='发送者id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
