# Generated by Django 2.1.3 on 2018-12-26 00:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('jobId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timeOfCreate', models.DateTimeField(auto_now_add=True)),
                ('jobName', models.CharField(default=None, max_length=50, verbose_name='职位名称')),
                ('description', models.CharField(default=None, max_length=400, verbose_name='职位介绍')),
                ('dueDate', models.DateTimeField(verbose_name='截止日期')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('CVId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(default=None, max_length=400, verbose_name='申请原因')),
                ('hobby', models.CharField(default=None, max_length=400, verbose_name='兴趣爱好')),
                ('eduBackground', models.CharField(default=None, max_length=400, verbose_name='教育背景')),
                ('inSchoolExp', models.CharField(default=None, max_length=400, verbose_name='校内经历')),
                ('outSchoolExp', models.CharField(default=None, max_length=400, verbose_name='校外经历')),
                ('isOpened', models.BooleanField(default=False)),
                ('isEnrolled', models.BooleanField(default=False)),
                ('isOfferd', models.BooleanField(default=False)),
                ('jobRelated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitAPI.JobList', verbose_name='相应职位')),
            ],
        ),
    ]
