# Generated by Django 2.1.3 on 2019-02-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTimetable',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='joblist',
            name='disabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='disabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
