# Generated by Django 2.1.3 on 2019-02-18 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitAPI', '0002_auto_20190217_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtimetable',
            name='disabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='interviewtimetable',
            name='location',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='interviewtimetable',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interviewtimetable',
            name='resume',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='RecruitAPI.Resume'),
        ),
    ]
