# Generated by Django 2.1.5 on 2019-02-11 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecruitAPI', '0003_auto_20190210_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resume',
            name='eduBackground',
            field=models.CharField(blank=True, default=None, max_length=400, verbose_name='教育背景'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='isReject',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='resume',
            name='outSchoolExp',
            field=models.CharField(blank=True, default=None, max_length=400, verbose_name='校外经历'),
        ),
    ]
