# Generated by Django 2.1.7 on 2019-02-19 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitAPI', '0004_auto_20190218_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewtimetable',
            options={'permissions': (('manage_interview_timetable', 'Can manage interview timetable'),)},
        ),
    ]
