# Generated by Django 2.1.5 on 2019-02-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitAPI', '0004_auto_20190211_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='additionMsg',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
    ]
