# Generated by Django 2.1.5 on 2019-02-12 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitAPI', '0005_resume_additionmsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='additionMsg',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='eduBackground',
            field=models.CharField(blank=True, default=None, max_length=400, null=True, verbose_name='教育背景'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='isEnrolled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='isOfferd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='isOpened',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='outSchoolExp',
            field=models.CharField(blank=True, default=None, max_length=400, null=True, verbose_name='校外经历'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
