# Generated by Django 2.1.5 on 2019-02-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitAPI', '0006_auto_20190212_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='isEnrolled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='isOfferd',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='isOpened',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='isReject',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
