# Generated by Django 2.2.3 on 2019-07-16 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAuthAPI', '0018_auto_20190509_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('prize_name', models.CharField(max_length=30)),
                ('prize_UserId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserAuthAPI.UserProfile')),
            ],
        ),
    ]
