# Generated by Django 2.1.7 on 2019-02-20 04:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPI', '0001_initial'),
        ('EventAPI', '0003_auto_20190220_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='relatedArticles',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='BlogAPI.Blog'),
        ),
        migrations.AlterField(
            model_name='event',
            name='maxAttendent',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
