# Generated by Django 2.1.7 on 2019-02-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventAPI', '0004_auto_20190220_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isMemberOnly',
            field=models.BooleanField(default=False),
        ),
    ]
