# Generated by Django 2.1.7 on 2019-02-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventAPI', '0005_event_ismemberonly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventActualStTime',
            field=models.DateTimeField(verbose_name='活动开始时间'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventInfo',
            field=models.CharField(max_length=600, verbose_name='活动简介'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventName',
            field=models.CharField(max_length=50, unique=True, verbose_name='活动名称'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventSignUpTime',
            field=models.DateTimeField(verbose_name='报名开始时间'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hasMaxAttendent',
            field=models.BooleanField(default=False, verbose_name='是否有人数上限?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='mainVisual',
            field=models.ImageField(default=None, null=True, upload_to='uploads/usrImage/', verbose_name='主视觉图'),
        ),
    ]
