# Generated by Django 2.1.7 on 2019-02-20 06:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventAPI', '0006_auto_20190220_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EventAPI.EventUndertaker', verbose_name='活动主办方'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventTypes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EventAPI.EventType', verbose_name='活动类型'),
        ),
        migrations.AlterField(
            model_name='event',
            name='isFree',
            field=models.BooleanField(default=True, verbose_name='是否为免费活动?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='isMemberOnly',
            field=models.BooleanField(default=False, verbose_name='是否为CSSA会员限定活动?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='maxAttendent',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='人数上限'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='门票价格'),
        ),
        migrations.AlterField(
            model_name='event',
            name='relatedArticles',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='BlogAPI.Blog', verbose_name='相关介绍文章'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='场馆名称'),
        ),
    ]
