# Generated by Django 2.1.7 on 2019-02-21 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventAPI', '0008_auto_20190220_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='DisplayArticleType',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='文章显示来源'),
        ),
        migrations.AddField(
            model_name='event',
            name='WechatArticleUrl',
            field=models.CharField(blank=True, default=True, max_length=200, null=True, verbose_name='微信公众号文章链接'),
        ),
        migrations.AlterField(
            model_name='event',
            name='relatedArticles',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='BlogAPI.Blog', verbose_name='相关介绍文章'),
        ),
    ]
