# Generated by Django 2.1.7 on 2019-02-22 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlexForm', '0001_initial'),
        ('EventAPI', '0011_auto_20190221_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendentInfoForm',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventAPI.Event')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlexForm.FlexForm')),
            ],
        ),
    ]
