# Generated by Django 2.1.7 on 2019-02-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventAPI', '0014_auto_20190223_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendevent',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
