# Generated by Django 2.1.5 on 2019-02-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventAPI', '0015_auto_20190224_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='WechatQRcode',
            field=models.ImageField(default=None, null=True, upload_to='uploads/usrImage/eventWechatQRcode', verbose_name='微信二维码'),
        ),
    ]
