# Generated by Django 2.2.1 on 2019-05-09 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventAPI', '0018_auto_20190303_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendevent',
            name='attendedUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserAuthAPI.UserProfile'),
        ),
    ]
