# Generated by Django 3.1.12 on 2021-11-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventAPI', '0019_auto_20190509_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pastEventLink',
            field=models.URLField(default=None, null=True, verbose_name='往期活动链接'),
        ),
        migrations.AddField(
            model_name='event',
            name='pastEventPoster',
            field=models.ImageField(default=None, null=True, upload_to='uploads/usrImage/eventPastVisual', verbose_name='往期活动海报'),
        ),
        migrations.AddField(
            model_name='event',
            name='recentEventLink',
            field=models.URLField(default=None, null=True, verbose_name='近期活动链接'),
        ),
        migrations.AddField(
            model_name='event',
            name='recentEventPoster',
            field=models.ImageField(default=None, null=True, upload_to='uploads/usrImage/eventRecentVisual', verbose_name='近期活动海报'),
        ),
    ]
