# Generated by Django 3.1.12 on 2021-12-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventAPI', '0020_auto_20211120_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pastEventLink',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pastEventPoster',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recentEventLink',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recentEventPoster',
        ),
        migrations.AddField(
            model_name='event',
            name='retrospectArticleLink',
            field=models.URLField(default=None, null=True, verbose_name='活动回顾（往期活动）文章链接'),
        ),
    ]
