# Generated by Django 2.1.7 on 2019-02-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventAPI', '0009_auto_20190221_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='DisplayArticleType',
            field=models.CharField(blank=True, choices=[('WeChat', 'WeChat'), ('Blog', 'Blog')], default=None, max_length=30, null=True, verbose_name='文章显示来源'),
        ),
    ]
