# Generated by Django 2.1.7 on 2019-02-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventAPI', '0010_auto_20190221_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='DisplayArticleType',
            field=models.CharField(choices=[('WeChat', 'WeChat'), ('Blog', 'Blog')], default=None, max_length=30, null=True, verbose_name='文章显示来源'),
        ),
        migrations.AlterField(
            model_name='event',
            name='WechatArticleUrl',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='微信公众号文章链接'),
        ),
    ]
