# Generated by Django 2.1.7 on 2019-02-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventAPI', '0016_event_wechatqrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendevent',
            name='token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
