# Generated by Django 2.1.7 on 2019-03-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventAPI', '0017_auto_20190226_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='WechatQRcode',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/usrImage/eventWechatQRcode', verbose_name='微信二维码'),
        ),
    ]
