# Generated by Django 2.1.3 on 2019-01-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0002_auto_20181229_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='originate',
            field=models.CharField(max_length=50, null=True, verbose_name='籍贯'),
        ),
    ]
