# Generated by Django 2.1.3 on 2018-12-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cssadept',
            name='deptTitle',
            field=models.CharField(default='Default', max_length=50, verbose_name='部门名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cssadept',
            name='deptTitleEN',
            field=models.CharField(default='Default', max_length=50, verbose_name='Name of the Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cssadept',
            name='deptName',
            field=models.CharField(max_length=50, verbose_name='部门简称'),
        ),
    ]
