# Generated by Django 2.1.3 on 2018-12-25 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0006_auto_20181221_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telNumber',
            field=models.CharField(default='0400000000', max_length=16, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
