# Generated by Django 2.1.3 on 2019-01-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0007_auto_20190104_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='originate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='籍贯'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='邮编'),
        ),
    ]
