# Generated by Django 2.1.3 on 2019-02-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0008_auto_20190106_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cssadept',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='public/department/', verbose_name='部门图'),
        ),
    ]
