# Generated by Django 2.1.3 on 2019-02-18 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthAPI', '0009_auto_20190217_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='cssacommitteprofile',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='UserAuthAPI.CSSARole'),
        ),
    ]
