# Generated by Django 2.1.3 on 2018-12-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppAccessControl',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('appName', models.CharField(max_length=500)),
                ('is_accessible', models.BooleanField(default=False)),
            ],
        ),
    ]
