# Generated by Django 2.1.3 on 2018-12-28 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myCSSAhub', '0002_auto_20181227_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_DB',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('content', models.CharField(max_length=200, null=True, verbose_name='站内信内容')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='站内信标题')),
                ('recID', models.ForeignKey(on_delete=models.DO_NOTHING, related_name='接受者id', to=settings.AUTH_USER_MODEL)),
                ('sendID', models.ForeignKey(on_delete=models.DO_NOTHING, related_name='发送者id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='messageID',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recID',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sendID',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationText',
        ),
    ]
