# Generated by Django 2.1.3 on 2019-01-04 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0005_notification_db_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_db',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='信息加入时间'),
        ),
    ]
