# Generated by Django 2.1.3 on 2019-01-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0006_auto_20190104_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('use_tls', models.BooleanField(default=False)),
                ('backend', models.CharField(max_length=200, null=True, verbose_name='后台')),
                ('host', models.CharField(max_length=200, null=True, verbose_name='发送方')),
                ('host_password', models.CharField(max_length=200, null=True, verbose_name='发送方密码')),
                ('host_user', models.CharField(max_length=200, null=True, verbose_name='发送方用户')),
                ('port', models.IntegerField(verbose_name='端口')),
            ],
        ),
    ]
