# Generated by Django 2.1.3 on 2019-01-09 04:50

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myCSSAhub', '0007_emailconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDB',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200, null=True, verbose_name='email内容')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='email标题')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='信息加入时间')),
                ('recID', models.ForeignKey(on_delete=None, related_name='接信者id', to=settings.AUTH_USER_MODEL)),
                ('sendID', models.ForeignKey(on_delete=None, related_name='发信者id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
