# Generated by Django 2.1.3 on 2019-01-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0007_emailconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfiguration',
            name='backend',
        ),
    ]
