# Generated by Django 2.1.3 on 2019-01-06 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0008_remove_emailconfiguration_backend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfiguration',
            name='host',
        ),
        migrations.RemoveField(
            model_name='emailconfiguration',
            name='use_tls',
        ),
    ]
