# Generated by Django 2.1.3 on 2019-01-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0008_emaildb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True, verbose_name='商家名')),
                ('description', models.CharField(max_length=256, null=True, verbose_name='商家介绍')),
                ('phone', models.CharField(max_length=256, null=True, verbose_name='联系电话')),
                ('link', models.CharField(max_length=256, null=True, verbose_name='商家网站')),
                ('logo', models.CharField(max_length=256, null=True, verbose_name='商家图片')),
            ],
        ),
    ]
