# Generated by Django 2.1.3 on 2019-01-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0009_merchants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchants',
            name='logo',
            field=models.ImageField(default='static/img/merchants/noneImg.jpg', upload_to='static/img/merchants/'),
        ),
    ]
