# Generated by Django 2.1.7 on 2019-03-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0014_discountmerchant_merchant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmerchant',
            name='merchant_type',
            field=models.CharField(choices=[('折扣商家', '折扣商家'), ('赞助商家', '赞助商家')], default='折扣商家', max_length=10, null=True, verbose_name='商户类型'),
        ),
    ]
