# Generated by Django 2.1.7 on 2019-03-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0016_auto_20190306_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountmerchant',
            name='merchant_Category',
            field=models.CharField(choices=[('美食', '美食'), ('休闲娱乐', '休闲娱乐'), ('便捷生活', '便捷生活')], default='美食', max_length=10, null=True, verbose_name='赞助商等级'),
        ),
        migrations.AddField(
            model_name='discountmerchant',
            name='merchant_level',
            field=models.CharField(choices=[('钻石商家', '钻石商家'), ('金牌商家', '金牌商家'), ('银牌商家', '银牌商家')], default='银牌商家', max_length=10, null=True, verbose_name='赞助商等级'),
        ),
    ]
