# Generated by Django 2.1.7 on 2019-03-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCSSAhub', '0017_auto_20190313_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountmerchant',
            name='merchant_qrcode',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/usrImage/merchantWechatQRcode', verbose_name='微信二维码'),
        ),
        migrations.AlterField(
            model_name='discountmerchant',
            name='merchant_Category',
            field=models.CharField(blank=True, choices=[('无', '无'), ('美食', '美食'), ('休闲娱乐', '休闲娱乐'), ('便捷生活', '便捷生活')], default='美食', max_length=10, null=True, verbose_name='折扣商家种类'),
        ),
        migrations.AlterField(
            model_name='discountmerchant',
            name='merchant_level',
            field=models.CharField(blank=True, choices=[('无', '无'), ('钻石商家', '钻石商家'), ('金牌商家', '金牌商家'), ('银牌商家', '银牌商家')], default='银牌商家', max_length=10, null=True, verbose_name='赞助商等级'),
        ),
    ]
