# Generated by Django 2.1.3 on 2018-12-02 04:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendEvent',
            fields=[
                ('attendedId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=50)),
                ('eventInfo', models.CharField(max_length=600)),
                ('eventStartTime', models.DateTimeField(auto_now_add=True)),
                ('eventSignUpTime', models.DateTimeField()),
                ('eventActualStTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('eventTypeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventUndertaker',
            fields=[
                ('eventTakerId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eventTakerName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TakerContacter',
            fields=[
                ('contacterId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contacterName', models.CharField(max_length=50)),
                ('contacterContact', models.CharField(max_length=50)),
                ('eventTakerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventAPI.EventUndertaker')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='eventBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EventAPI.EventUndertaker'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventTypes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EventAPI.EventType'),
        ),
        migrations.AddField(
            model_name='attendevent',
            name='attendedEventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventAPI.Event'),
        ),
    ]
