# Generated by Django 2.1.3 on 2018-12-26 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FinanceAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransferRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('bsb', models.CharField(max_length=6)),
                ('acc_number', models.CharField(max_length=11)),
                ('pic_scan', models.ImageField(blank=True, null=True, upload_to='finance/bankreceipient/')),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('related_transactions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinanceAPI.Transaction')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
