# Generated by Django 2.1.3 on 2018-12-28 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FinanceAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransferrecipient',
            name='related_transactions',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='related_transactions',
        ),
        migrations.AddField(
            model_name='banktransferrecipient',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinanceAPI.Transaction'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinanceAPI.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
