# Generated by Django 2.1.3 on 2018-12-27 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAPI', '0002_banktransferrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='banktransferrecipient',
            name='related_transactions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinanceAPI.Transaction'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='related_transactions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinanceAPI.Transaction'),
        ),
    ]
