# Generated by Django 2.1.3 on 2018-12-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAPI', '0003_auto_20181227_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransferrecipient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
