# Generated by Django 2.2 on 2019-04-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlexForm', '0003_auto_20190223_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexformfield',
            name='field_type',
            field=models.CharField(choices=[('文本', 'text'), ('数字', 'digit'), ('文件', 'file')], max_length=10, verbose_name='字段类型'),
        ),
    ]
